### PR TITLE
fix a regression, closes #1559

### LINKED ISSUE #1559: Sinatra 2.0.6 regression: OptionParser::InvalidOption:   invalid option: --pattern
Error:

    OptionParser::InvalidOption:
      invalid option: --pattern
    # /var/lib/gems/2.5.0/gems/sinatra-2.0.6/lib/sinatra/main.rb:18:in `<module:Sinatra>'

Reproduction instructions:

$ git clone https://github.com/rubys/sinatra206.git
$ cd sinatra206
$ bundle install
$ bundle exec rake test

This worked with Sinatra 2.0.5.  See also https://travis-ci.org/apache/whimsy/jobs/574961311

### PR DESCRIPTION
**Pull request by namusyaka**
#1559

### CODE REVIEW

File: lib/sinatra/main.rb [hunk 1]
```diff
@@ -29,7 +34,11 @@ class Application < Base
 
     set :run, Proc.new { File.expand_path($0) == File.expand_path(app_file) }
 
-    ParamsConfig.each { |k, v| set k, v } if run? && ARGV.any?
+    if run? && ARGV.any?
+      error = ParamsConfig.delete(:optparse_error)
+      raise error if error
```
Comment (jkowens) [inline lib/sinatra/main.rb]: Do we need to raise an invalid option error, or could we just swallow and ignore?

Comment (namusyaka) [reply lib/sinatra/main.rb]: We should raise this.
Because if we ignore that, actual invalid error can not be handled.
Developer may use "require "sinatra" with "foo.rb" then exec "ruby foo.rb --opts"

If the command are "ruby foo.rb --invalidopts", then sinatra should raise an error.
