### PR TITLE
avoid prefix duplication

### LINKED ISSUE #1310: Nested Namespaces worked in 1.4.8, broken in 2.0.0
I'm not sure if nested namespaces are actually supported as I don't see any specific mention of them in the docs. Anyhow in Sinatra 1.4.8 I could define an app like:

```ruby
require 'sinatra'
require 'sinatra/contrib'
require 'json'

BOOKS = {
  1 => {name: 'The Lord of the Rings'},
  2 => {name: 'The Chronicles of Narnia'},
  3 => {name: 'Harry Potter'},
}

namespace '/api' do
  namespace '/v1' do
    namespace '/books' do
      get do
        body JSON.dump(BOOKS)
      end
    end
  end
end
```

cURLing the endpoint:

```bash
$ curl localhost:4567/api/v1/books
{"1":{"name":"The Lord of the Rings"},"2":{"name":"The Chronicles of Narnia"},"3":{"name":"Harry Potter"}}
```

Now if I define a similar app in Sinatra 2.0.0:

```ruby
require 'sinatra'
require 'sinatra/contrib'
require 'json'

BOOKS = {
  1 => {name: 'The Lord of the Rings'},
  2 => {name: 'The Chronicles of Narnia'},
  3 => {name: 'Harry Potter'},
}

namespace '/api' do
  namespace '/v1' do
    namespace '/books' do
      get do
        body JSON.dump(BOOKS)
      end
    end
  end
end
```

And then cURL the same path:

```bash
$  curl localhost:4567/api/v1/books
<!DOCTYPE html>
<html>
<head>
  <style type="text/css">
  body { text-align:center;font-family:helvetica,arial;font-size:22px;
    color:#888;margin:20px}
  #c {margin:0 auto;width:500px;text-align:left}
  </style>
</head>
<body>
  <h2>Sinatra doesn’t know this ditty.</h2>
  <img src='http://localhost:4567/__sinatra__/404.png'>
  <div id="c">
    Try this:
    <pre>get &#x27;&#x2F;api&#x2F;v1&#x2F;books&#x27; do
  &quot;Hello World&quot;
end
</pre>
  </div>
</body>
</html>
```

With this 2.0.0 Sintra app I decided to list all the GET paths:

```ruby
Sinatra::Application.routes["GET"].each do |route|
  puts route[0]
end
```

Which results in:

```
/api/v1/v1/books
```

If I cURL that path I get a successful result:

```bash
$  curl localhost:4567/api/v1/v1/books
{"1":{"name":"The Lord of the Rings"},"2":{"name":"The Chronicles of Narnia"},"3":{"name":"Harry Potter"}}
```

The repeated v1/v1 is not expected. Sinatra 1.4.8's `/api/v1/books` is the behaviour I would have expected.

Is this supposed to work? If there is a better way to define nested namespaces please let me know.

### PR DESCRIPTION
**Pull request by namusyaka**
Fixes #1310 
@aren55555 @mencargo @zzak Could you confirm this?

### CODE REVIEW

**Comment by aren55555** [comment]
Looks like this branch works. LGTM.

Gemfile:
```
github 'namusyaka/sinatra', branch: 'fix-1310' do
  gem 'sinatra'
  gem 'sinatra-contrib'
end
```

File: sinatra-contrib/lib/sinatra/namespace.rb [hunk 1]
```diff
@@ -319,7 +319,6 @@ def compile(pattern, conditions, default_pattern = nil)
         end
         base_pattern, base_conditions = @pattern, @conditions
         pattern         ||= default_pattern
-        base_pattern    ||= base.pattern    if base.respond_to? :pattern
         base_conditions ||= base.conditions if base.respond_to? :conditions
```
Comment (namusyaka) [inline sinatra-contrib/lib/sinatra/namespace.rb]: Ah, yes. However, it should be treated as a different issue.
Briefly, that `conditions` has not been permanently satisfied, so I deleted it as new commit.
