### PR TITLE
Handle EOFError raised by Rack and raise BadRequest (and lock Rack version to 2.0 to pass tests)

### LINKED ISSUE #1739: Getting 500 EOFError when malformed multipart/form-data POST request arrives
Sinatra crashes when malformed POST request arrives by EOFError. The POST request has "Content-Type: form/multi-part" header, but does not have any content in its body.
It should be handled and return 400 (Bad Request) instead of 500.

# How to reproduce this Error
1. make sinatra app just like GETTING STARTED and install sinatra(2.1.0)
2. start local server with `ruby myapp.rb`
3. send a malformed POST request with curl (has multipart/form-data header without content)
  `curl -v -X POST -H 'Content-Type: multipart/form-data; boundary=dummy' http://localhost:4567/post-end-point`
4. Sinatra returns `HTTP/1.1 500 Internal Server Error`
<details>
<summary>Click to Open Error log</summary>

```
EOFError: EOFError
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:359:in `handle_empty_content!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:186:in `on_read'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart/parser.rb:73:in `parse'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/multipart.rb:54:in `extract_multipart'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:594:in `parse_multipart'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:446:in `POST'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:469:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/request.rb:32:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:78:in `params'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1118:in `dispatch!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `block in call!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `block in invoke'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `catch'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1101:in `invoke'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:939:in `call!'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:929:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/json_csrf.rb:26:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/base.rb:50:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-protection-2.1.0/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/logger.rb:17:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/common_logger.rb:38:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:253:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:246:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/show_exceptions.rb:22:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:216:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1991:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `block in call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1769:in `synchronize'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/sinatra-2.1.0/lib/sinatra/base.rb:1542:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'
	/Users/user/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'

```

</details>

As a workaround, I applied a patch to Sinatra::Request#params to consider the error as a bad request:
```
# my patch
# frozen_string_literal: true

require "sinatra/base"

module Sinatra
  class Request
    def params
      super
    rescue Rack::Utils::ParameterTypeError, Rack::Utils::InvalidParameterError => e
      raise BadRequest, "Invalid query parameters: #{Rack::Utils.escape_html(e.message)}"
    rescue EOFError => e
      raise BadRequest, "Invalid multipart/form-data: #{Rack::Utils.escape_html(e.message)}"
    end
  end
end
```
I'll make a PR if you like it.

### PR DESCRIPTION
**Pull request by tamazon**
This fixes #1739. Now Sinatra returns 400 Bad Request instead of 500.

### CODE REVIEW

**Comment by tamazon** [comment]
I can't understand why this case fails. I need help.
```
  1) Failure:
RoutingTest#test_handles_params_without_a_value_0 [/home/runner/work/sinatra/sinatra/test/routing_test.rb:317]:
Expected "" to be nil.
```

1. I also tried running this test on master branch and older releases and it still fails.
2. It works when I change Rack version from 2.3.0 to 2.2.3.

I assume this is problem of Rack but I have no idea why it happens and why Gemfile specifies rack's main branch to install.

**Comment by tamazon** [comment]
https://github.com/rack/rack/issues/1696
This is probably the change that causes this behavior.

from CHANGELOG of 3.0.0

> BREAKING CHANGE: Query parsing now treats parameters without = as having the empty string value instead of nil value, 
>  to conform to the URL spec. ([#1696](https://github.com/rack/rack/issues/1696), @jeremyevans)

**Comment by tamazon** [comment]
I guess changing [this line](https://github.com/sinatra/sinatra/blob/e69b6b9dee7165d3a583fc8a6af10ceee1ea687d/test/routing_test.rb#L317) from: `assert_nil params.fetch('foo')` to: `assert_equal '', params.fetch('foo')` fix this problem.
I'm not sure it's appropriate to do so.

**Comment by jkowens** [comment]
I think we can lock the Gemfile to rack '~> 2.0' for now.

File: Gemfile [hunk 1]
```diff
@@ -11,7 +11,7 @@ source 'https://rubygems.org' unless ENV['QUICK']
 gemspec
 
 gem 'rake'
-gem 'rack', git: 'https://github.com/rack/rack.git'
+gem 'rack', '~> 2.0'
```
Comment (tamazon) [inline Gemfile:14]: Locked to 2.0 to pass tests

File: lib/sinatra/base.rb [hunk 2]
```diff
@@ -78,6 +78,8 @@ def params
       super
     rescue Rack::Utils::ParameterTypeError, Rack::Utils::InvalidParameterError => e
       raise BadRequest, "Invalid query parameters: #{Rack::Utils.escape_html(e.message)}"
+    rescue EOFError => e
+      raise BadRequest, "Invalid multipart/form-data: #{Rack::Utils.escape_html(e.message)}"
```
Comment (ioquatix) [inline lib/sinatra/base.rb:82]: It's not clear to me why you escape the HTML here, rather than on the output formatting side.

Comment (dentarg) [reply lib/sinatra/base.rb:82]: I can only provide background info, not speak to if this is the best solution. The introduction of handling of `EOFError` probably just followed what was already there: the handling of invalid query parameters – escaping those was introduced in https://github.com/sinatra/sinatra/pull/1432 to address an reported XSS https://github.com/sinatra/sinatra/issues/1428 (the initial handling of invalid query parameters was added in https://github.com/sinatra/sinatra/pull/1070)

Feel free to make a PR if you have a more appropriate solution.

Comment (dentarg) [reply lib/sinatra/base.rb:82]: I think it makes sense to escape here as otherwise every application outputting the `BadRequest` message would need to do it.

Comment (ioquatix) [reply lib/sinatra/base.rb:82]: You should escape any error messages regardless because you don't control every error message generation, right? It should be escaped when generating HTML from the error message, not when creating an exception. Otherwise, how do you  print this to the command-line, log file, etc. Maybe I'm misunderstanding something.

Comment (dentarg) [reply lib/sinatra/base.rb:82]: Sure, what you say makes sense. Feel free to contribute and maybe others will weigh in as well.

Comment (tamazon) [reply lib/sinatra/base.rb:82]: Thanks for mentioning. To be honest, I just copied lines above and changed error type and message. I didn't think about whether this usage of escape_html was correct or not.
